---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      # watchdog
      #- /sbin/modprobe:/sbin/modprobe:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - patroni
  - name: instance-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      # watchdog
      #- /sbin/modprobe:/sbin/modprobe:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - patroni
provisioner:
  name: ansible
verifier:
  name: ansible
