---
- include_tasks: variables.yml

- import_tasks: install.yml
  tags: [patroni, patroni-install]

- import_tasks: configure.yml
  tags: [patroni, patroni-configure]

- meta: flush_handlers

- name: Register journalctl -xe output
  command: 'journalctl -xe'
  register: command_output
  changed_when: false

- name: Print 'find / | grep libcrypto.so.1.1' output
  debug:
    msg: "{{ command_output.stdout_lines }}"

- name: Ensure patroni is running
  systemd:
    name: patroni.service
    state: started
    daemon_reload: yes
    enabled: yes
  tags: [patroni]

- name: Ensure haproxy is running
  systemd:
    name: haproxy.service
    state: started
    daemon_reload: yes
    enabled: yes
  when: patroni_install_haproxy
