---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh yum cache
      yum:
        update_cache: yes

    #- name: Install required packages for EL 7
    #  package:
    #    name:
    #      - openssl11-libs
    #      - libzstd-devel
    #  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: Create /etc/udev/rules.d
      file:
        path: /etc/udev/rules.d
        state: directory
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
