---
name: KICS Security Scan
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
  push:
    branches:
      - 'main'
      - 'netways'
  merge_group:
  schedule:
    - cron: '15 6 * * 4'
jobs:
  kics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: run kics Scan
        uses: Checkmarx/kics-github-action@c11ca46d31795a2f186f1af610d121e3bcd647a0 #v2.1.14
        with:
          # path: 'roles,plugins'
          path: '.'
          fail_on: high
          ignore_on_exit: results
          output_formats: 'json,sarif'
          output_path: results-dir
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 #v3.29.5
        with:
          sarif_file: results-dir/results.sarif
